var apiurl = 'http://api.77x6.com/inc/';
document.writeln("<style type=\"text/css\">");
document.writeln("tr a {");
document.writeln("	font-size: 12px;");
document.writeln("	color: #666;");
document.writeln("}");
document.writeln("tr a:link {");
document.writeln("	text-decoration: none;");
document.writeln("}");
document.writeln("tr a:visited {");
document.writeln("	text-decoration: none;");
document.writeln("	color: #666;");
document.writeln("}");
document.writeln("tr a:hover {");
document.writeln("	text-decoration: underline;");
document.writeln("	color: #FF0000;");
document.writeln("}");
document.writeln("tr a:active {");
document.writeln("	text-decoration: none;");
document.writeln("	color: #f60;");
document.writeln("}");
document.writeln("tr{}");
document.writeln("td{ background-color: #fff; height:30px; line-height:30px;font-size: 12px; color: #333;border:1px solid #E7E8EA;text-align:center;}");
document.writeln(".bi{width:78%;text-align:left;padding-left:10px;}");
document.writeln(".b2{text-align:left;padding-left:10px; color: #333;}");
document.writeln(".der{border:1px solid #E7E8EA;}");
document.writeln("</style>");

document.writeln("<div style=\"height:10px; clear:both;\">&nbsp;</div>");
document.writeln("<table width=\"98%\"  align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" bgcolor=\"#fff\">");
document.writeln("   <tr>");
document.writeln("    <td width=\"2%\">1</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url=http://down.77x6.com/inc/apixunlei.php\">【迅雷下载资源测试】</a></td>");
document.writeln("    <td width=\"5%\"><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url=http://down.77x6.com/inc/apixunlei.php\">采集当天</a></td>");
document.writeln("    <td width=\"5%\"><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url=http://down.77x6.com/inc/apixunlei.php\">采集本周</a></td>");
document.writeln("    <td width=\"5%\"><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url=http://down.77x6.com/inc/apixunlei.php\">采集所有</a></td>");
document.writeln("    <td width=\"5%\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url=http://down.77x6.com/inc/apixunlei.php\">分类绑定</a></td>");
document.writeln("  </tr>");
document.writeln("   <tr>");
document.writeln("    <td>2</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"api.php\">【全部资源】一键采集资源</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url="+apiurl+"api.php\">采集当天</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url="+apiurl+"api.php\">采集本周</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url="+apiurl+"api.php\">采集所有</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"api.php\">分类绑定</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td >3</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apiyouku.php\">【优酷资源】一键采集资源</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url="+apiurl+"apiyouku.php\">采集当天</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url="+apiurl+"apiyouku.php\">采集本周</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url="+apiurl+"apiyouku.php\">采集所有</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apiyouku.php\">分类绑定</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td>4</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apiletv.php\">【乐视资源】一键采集资源</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url="+apiurl+"apiletv.php\">采集当天</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url="+apiurl+"apiletv.php\">采集本周</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url="+apiurl+"apiletv.php\">采集所有</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apiletv.php\">分类绑定</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td>5</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apimgtv.php\">【芒果资源】一键采集资源</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url="+apiurl+"apimgtv.php\">采集当天</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url="+apiurl+"apimgtv.php\">采集本周</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url="+apiurl+"apimgtv.php\">采集所有</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apimgtv.php\">分类绑定</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td>6</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apim1905.php\">【电影网资源】一键采集资源</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url="+apiurl+"apim1905.php\">采集当天</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url="+apiurl+"apim1905.php\">采集本周</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url="+apiurl+"apim1905.php\">采集所有</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apim1905.php\">分类绑定</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td>7</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apiqq.php\">【腾讯资源】一键采集资源</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url="+apiurl+"apiqq.php\">采集当天</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url="+apiurl+"apiqq.php\">采集本周</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url="+apiurl+"apiqq.php\">采集所有</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apiqq.php\">分类绑定</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td>8</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apitudou.php\">【土豆资源】一键采集资源</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url="+apiurl+"apitudou.php\">采集当天</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url="+apiurl+"apitudou.php\">采集本周</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url="+apiurl+"apitudou.php\">采集所有</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apitudou.php\">分类绑定</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td>9</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apipptv.php\">【PPTV资源】一键采集资源</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url="+apiurl+"apipptv.php\">采集当天</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url="+apiurl+"apipptv.php\">采集本周</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url="+apiurl+"apipptv.php\">采集所有</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apipptv.php\">分类绑定</a></td>");
document.writeln("  </tr>");
document.writeln("  <tr>");
document.writeln("    <td>10</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apisouhu.php\">【搜狐资源】一键采集资源</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url="+apiurl+"apisouhu.php\">采集当天</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url="+apiurl+"apisouhu.php\">采集本周</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url="+apiurl+"apisouhu.php\">采集所有</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url="+apiurl+"apisouhu.php\">分类绑定</a></td>");
document.writeln("  </tr>");

document.writeln("  <tr>");
document.writeln("    <td>11</td>");
document.writeln("    <td class=\"bi\"><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url=http://www.91zy.cc/inc/api.asp\">【混合资源】一键采集资源(需播放器支持)</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=day&rid=77x6.com&url=http://www.91zy.cc/inc/api.asp\">采集当天</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=week&rid=77x6.com&url=http://www.91zy.cc/inc/api.asp\">采集本周</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=all&rid=77x6.com&url=http://www.91zy.cc/inc/api.asp\">采集所有</a></td>");
document.writeln("    <td><a href=\"admin_reslib.php?ac=list&rid=77x6.com&url=http://www.91zy.cc/inc/api.asp\">分类绑定</a></td>");
document.writeln("  </tr>");
document.writeln("</table>");
